# Generated by Django 3.1 on 2020-09-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
